### PR TITLE
pass useQueryParamsInCacheKey to getCacheKey

### PR DESCRIPTION
**Pull request by bajceta**

### CODE REVIEW

**Comment by kfiroo** [comment]
@bajceta Thanks for the PR! :)
Can you provide some motivation behind it?
Why is it needed?

**Comment by bajceta** [comment]
2 images that share the same url, but have different query parameters will have the same filepath even when using useQueryParamsInCacheKey.
In our case we resize images serverside, so the base url is the same for all pictures. End result was that a single image was used everywhere :)

**Comment by kfiroo** [comment]
@bajceta Good catch! Thanks! 

_NOTE:  Looks like some other commits found their way into this PR, was that intentional?_

Regarding the original issue, the bug is actually [here](https://github.com/kfiroo/react-native-cached-image/blob/3d005abc2a2f40929431a6866d73592752d00a6f/utils/pathUtils.js#L40).
We know the url used in `path.getImageFilePath` is a `cacheableUrl` which was already stripped of unused query params.

I think the cleanest fix is to add a default value to the `useQueryParamsInCacheKey` param in `generateCacheKey`

```jsx
function generateCacheKey(url, useQueryParamsInCacheKey = true) {
    const parsedUrl = new URL(url, null, true);
    // ...
    const cacheable = filePath + fileName + type + getQueryForCacheKey(parsedUrl, useQueryParamsInCacheKey);
    return SHA1(cacheable) + '.' + type;
}
```

Let me know if that works for you :)

**Comment by bajceta** [comment]
Other commits were a mistake, my bad :)
I guess the cleanest option then would be to remove `useQueryParamsInCacheKey` argument from 
`getQueryForCacheKey` because as you said it was already stripped in `getCachedUrl`, so there should be no need, except for a small performance benefit?

What do you think?
I will try it out tomorrow.

**Comment by kfiroo** [comment]
@bajceta I agree, setting the default value to `true` and removing the param will both work fine.
I like the default param option only because it give more flexibility in the future if we want to use this method differently.

**Comment by bajceta** [comment]
I updated the PR, with the default param. 
Works for me :)

**Comment by kfiroo** [comment]
@bajceta Great! :)

**Pull request merged**
