### PR TITLE
Listen NetInfo connectionChange event (change deprecated)

### LINKED ISSUE #75: NetInfo's "change" event is deprecated
After upgrading to latest React Native (0.48.0) I keep getting this warning:

`NetInfo's "change" event is deprecated. Listen to the "connectionChange" event instead.`

I guess this is due to: https://github.com/kfiroo/react-native-cached-image/blob/6aac3174f4404a29cb8b3a259290ad0f28ae47f3/CachedImage.js#L90

### PR DESCRIPTION
**Pull request by kytwb**
Fixes #75

### CODE REVIEW

**Comment by kfiroo** [comment]
@kytwb Great, thanks!
Just a quick question, would that cause a problem for users with lower versions of RN? (I think it's polite to support at least 1-2 previous versions)

**Comment by kytwb** [comment]
@kfiroo I'll check and make it backward compatible if possible.
If not possible, what should I do? Follow semver and major/minor the version?

**Comment by kfiroo** [comment]
@kytwb Thanks! 
If you can't make it backward compatible we should merge it after the 1.4 version, which already forces users to upgrade

**Comment by chrusart** [comment]
Will this work?
https://github.com/facebook/react-native/issues/12503
just check if RN >= 0.48.0 then use connectionChange event name

**Pull request merged**
